FROM node:16-alpine as builder
USER node
WORKDIR /app
COPY --chown=node:node jobs/package.json .
RUN yarn install
COPY --chown=node:node jobs .
RUN yarn build
 
FROM node:16-alpine
USER node
ENV NODE_ENV=prod
WORKDIR /app
COPY --from=builder --chown=node:node /jobs/package.json .
EXPOSE 3000
RUN yarn install --production=true
COPY --from=builder --chown=node:node /jobs/prisma .
COPY --from=builder --chown=node:node /jobs/dist dist
CMD [ "yarn", "start:prod:vote-processor" ]
