services:
  api:
    container_name: ranked-choice-voting-api
    build:
      context: ..
      dockerfile: docker/Dockerfile.app.prod
      # dockerfile: docker/Dockerfile.app.dev
    ports:
      - 3000:3000
    env_file:
      - ../config/app.env
    depends_on:
      - rabbitmq
      - redis
      - postgres
    links:
      - rabbitmq
      - redis
      - postgres

  redis:
    container_name: ranked-choice-voting-redis
    image: redis
    env_file:
      - ../config/redis.env

  rabbitmq:
    container_name: ranked-choice-voting-rabbitmq
    image: rabbitmq
    env_file:
      - ../config/rabbitmq.env

  postgres:
    container_name: ranked-choice-voting-postgres
    image: postgres
    env_file:
      - ../config/postgres.env
    ports:
      - 5432:5432
