services:
  api:
    container_name: ranked-choice-voting-api
    build:
      context: ..
      dockerfile: docker/Dockerfile.app.prod
      # dockerfile: docker/Dockerfile.app.dev
    ports:
      - 3000:3000
    env_file:
      - ../config/app.env
    depends_on:
      - rabbitmq
      - redis
      - postgres
    links:
      - rabbitmq
      - redis
      - postgres

  jobs:
    container_name: ranked-choice-voting-jobs
    build:
      context: ..
      dockerfile: docker/Dockerfile.jobs.prod
      # dockerfile: docker/Dockerfile.jobs.dev
    env_file:
      - ../config/app.env
    depends_on:
      - api
      - rabbitmq
      - redis
      - postgres
    links:
      - rabbitmq
      - redis
      - postgres

  redis:
    container_name: ranked-choice-voting-redis
    image: redis
    volumes:
      - ../volumes/redis/data:/data
    env_file:
      - ../config/redis.env
    ports:
      - 6379:6379

  rabbitmq:
    container_name: ranked-choice-voting-rabbitmq
    image: rabbitmq
    env_file:
      - ../config/rabbitmq.env
    ports:
      - 5672:5672

  postgres:
    container_name: ranked-choice-voting-postgres
    image: postgres
    volumes:
      - ../volumes/postgres/data:/var/lib/postgresql/data
    env_file:
      - ../config/postgres.env
    ports:
      - 5432:5432
